/**
 * GENERATED by tools/solve-locations.ts -- do not edit by hand.
 *
 * Named locations in signing space, solved to concrete arm rotations. Shoulder
 * and elbow are XYZ Euler degrees; wristCorrection is the quaternion that
 * leaves the hand palm-out and fingers-up once the arm is in place, so a sign's
 * own orientation composes on top of it as a delta.
 *
 * Run `pnpm solve:locations` to regenerate.
 */

export interface SolvedLocation {
  readonly description: string;
  /** The wrist position this was solved for, in metres. */
  readonly target: readonly [number, number, number];
  readonly shoulder: readonly [number, number, number];
  readonly elbow: readonly [number, number, number];
  readonly wristCorrection: readonly [number, number, number, number];
}

export const SOLVED_LOCATIONS = {
  NEUTRAL: {
    description: "Default signing space, chest height and well forward",
    target: [-0.17, 1.24, 0.26],
    shoulder: [12.1406, 38.2266, 11.25],
    elbow: [59.8125, -13.8047, 11.8594],
    wristCorrection: [-0.5907, -0.1838, 0.0352, 0.7849],
  },
  NEUTRAL_HIGH: {
    description: "Upper signing space",
    target: [-0.17, 1.36, 0.26],
    shoulder: [-16.2544, 10.4602, -4.2782],
    elbow: [59.1136, -15.5563, -28.5906],
    wristCorrection: [-0.3538, -0.0111, 0.3576, 0.8642],
  },
  NEUTRAL_LOW: {
    description: "Lower signing space",
    target: [-0.16, 1.12, 0.24],
    shoulder: [5.8182, 45.7521, 34.1823],
    elbow: [30.5357, 32.6683, 47.2622],
    wristCorrection: [-0.5415, -0.4499, -0.5221, 0.4815],
  },
  CHEST: {
    description: "At the chest, close enough to read as contact",
    target: [-0.09, 1.27, 0.12],
    shoulder: [20.6716, 14.6796, 13.9932],
    elbow: [28.3985, -28.0131, -45.5739],
    wristCorrection: [-0.4361, -0.0915, 0.3409, 0.8278],
  },
  CHIN: {
    description: "At the chin",
    target: [-0.08, 1.47, 0.17],
    shoulder: [-19.849, 51.3575, -19.4401],
    elbow: [31.6776, -28.1989, -19.8465],
    wristCorrection: [0.0753, -0.0801, 0.4751, 0.873],
  },
  MOUTH: {
    description: "At the mouth",
    target: [-0.06, 1.5, 0.15],
    shoulder: [-9.3271, 57.8904, -53.1244],
    elbow: [39.2105, -2.4879, -13.517],
    wristCorrection: [0.0442, -0.2124, 0.6268, 0.7484],
  },
  FOREHEAD: {
    description: "At the forehead",
    target: [-0.1, 1.62, 0.13],
    shoulder: [-41.0952, 63.0837, -25.0236],
    elbow: [34.4089, 7.1021, 7.7882],
    wristCorrection: [0.1095, -0.3495, 0.4121, 0.8343],
  },
  TEMPLE: {
    description: "Beside the temple",
    target: [-0.17, 1.6, 0.07],
    shoulder: [3.3107, 20.3126, -74.129],
    elbow: [11.0361, -21.5601, 7.8581],
    wristCorrection: [0.1228, 0.0413, 0.5334, 0.8359],
  },
  SHOULDER: {
    description: "At the dominant shoulder",
    target: [-0.24, 1.4, 0.12],
    shoulder: [26.2451, 8.2257, -14.0541],
    elbow: [17.2321, -12.0028, -13.4645],
    wristCorrection: [-0.3439, -0.0241, 0.2604, 0.9018],
  },
  OUT_HIGH: {
    description: "Up and out, where a salute releases to",
    target: [-0.3, 1.54, 0.2],
    shoulder: [1.3616, 30.1543, -30.3854],
    elbow: [13.4742, 18.188, 23.2058],
    wristCorrection: [-0.168, -0.3407, 0.0827, 0.9213],
  },
  SIDE_MID: {
    description: "Out to the dominant side",
    target: [-0.29, 1.26, 0.22],
    shoulder: [6.0574, 8.0748, 23.676],
    elbow: [50.9559, 2.8367, 9.8851],
    wristCorrection: [-0.4867, -0.1214, -0.247, 0.8291],
  },
  CENTRE_LOW: {
    description: "Centred and low, where a base hand sits",
    target: [-0.05, 1.16, 0.24],
    shoulder: [1.5889, 18.1367, 34.6475],
    elbow: [93.2924, 7.9227, -8.3348],
    wristCorrection: [-0.6899, -0.4079, -0.1043, 0.5889],
  },
  CENTRE_MID: {
    description: "Centred, just above the base hand, where a dominant hand taps down",
    target: [-0.04, 1.29, 0.25],
    shoulder: [-3.4634, 52.9713, 15.6724],
    elbow: [64.0742, 0.8061, -0.0982],
    wristCorrection: [-0.5006, -0.4407, 0.1412, 0.7316],
  },
  EAR: {
    description: "Beside the ear",
    target: [-0.19, 1.57, 0.02],
    shoulder: [-33.4319, 17.3588, -55.7808],
    elbow: [20.1216, 34.3346, -7.6929],
    wristCorrection: [0.0354, -0.1665, 0.5582, 0.8121],
  },
} as const satisfies Record<string, SolvedLocation>;

export type LocationName = keyof typeof SOLVED_LOCATIONS;
