/**
 * GENERATED by tools/solve-locations.ts -- do not edit by hand.
 *
 * Named locations in signing space, solved to concrete arm rotations. Shoulder
 * and elbow are XYZ Euler degrees; wristCorrection is the quaternion that
 * leaves the hand palm-out and fingers-up once the arm is in place, so a sign's
 * own orientation composes on top of it as a delta.
 *
 * Run `pnpm solve:locations` to regenerate.
 */

export interface SolvedLocation {
  readonly description: string;
  /** The point in signing space this names, in metres. */
  readonly target: readonly [number, number, number];
  readonly shoulder: readonly [number, number, number];
  readonly elbow: readonly [number, number, number];
  readonly wristCorrection: readonly [number, number, number, number];
}

export const SOLVED_LOCATIONS = {
  NEUTRAL: {
    description: "Default signing space, chest height and well forward",
    target: [-0.17, 1.24, 0.26],
    shoulder: [12.1406, 38.2266, 11.25],
    elbow: [59.8125, -13.8047, 11.8594],
    wristCorrection: [-0.5907, -0.1838, 0.0352, 0.7849],
  },
  NEUTRAL_HIGH: {
    description: "Upper signing space",
    target: [-0.17, 1.36, 0.26],
    shoulder: [12.7173, 50.2166, -5.6642],
    elbow: [39.2605, -9.351, 12.3819],
    wristCorrection: [-0.3986, -0.2926, 0.0782, 0.8657],
  },
  NEUTRAL_LOW: {
    description: "Lower signing space",
    target: [-0.16, 1.12, 0.24],
    shoulder: [12.1312, 33.7706, 22.3519],
    elbow: [74.663, 5.4984, 20.2201],
    wristCorrection: [-0.7389, -0.2444, -0.1528, 0.609],
  },
  CHEST: {
    description: "At the chest, close enough to read as contact",
    target: [-0.09, 1.27, 0.12],
    shoulder: [1.4716, 25.7783, -14.9594],
    elbow: [15.9529, -25.6552, -63.3666],
    wristCorrection: [-0.0764, -0.0298, 0.665, 0.7423],
  },
  CHIN: {
    description: "At the chin",
    target: [-0.08, 1.47, 0.17],
    shoulder: [-40.8465, 18.0231, 32.6739],
    elbow: [35.4389, -19.8887, -35.8431],
    wristCorrection: [0.0174, -0.1222, 0.1851, 0.9749],
  },
  MOUTH: {
    description: "At the mouth",
    target: [-0.06, 1.5, 0.15],
    shoulder: [-53.5721, 40.9627, 28.1545],
    elbow: [41.7834, -9.1804, -23.4074],
    wristCorrection: [0.0815, -0.3126, 0.2855, 0.9023],
  },
  FOREHEAD: {
    description: "At the forehead",
    target: [-0.1, 1.62, 0.13],
    shoulder: [-51.6308, 82.4501, -3.2815],
    elbow: [20.6661, -4.0703, 17.6682],
    wristCorrection: [0.1546, -0.5233, 0.28, 0.7899],
  },
  TEMPLE: {
    description: "Beside the temple",
    target: [-0.17, 1.6, 0.07],
    shoulder: [-28.7176, 80.7602, -30.788],
    elbow: [3.0144, -13.7054, 9.0567],
    wristCorrection: [0.3347, -0.4887, 0.2639, 0.7612],
  },
  SHOULDER: {
    description: "At the dominant shoulder",
    target: [-0.24, 1.4, 0.12],
    shoulder: [-6.4275, -2.9484, 28.3609],
    elbow: [21.1947, -9.9943, -18.0862],
    wristCorrection: [-0.1452, 0.0272, -0.0786, 0.9859],
  },
  OUT_HIGH: {
    description: "Up and out, where a salute releases to",
    target: [-0.3, 1.54, 0.2],
    shoulder: [-26.4355, 42.0907, -3.2815],
    elbow: [13.213, 6.9218, 23.9963],
    wristCorrection: [0.0264, -0.3981, -0.0376, 0.9162],
  },
  SIDE_MID: {
    description: "Out to the dominant side",
    target: [-0.29, 1.26, 0.22],
    shoulder: [7.0676, 22.3028, 24.2977],
    elbow: [28.1552, 29.738, 23.3259],
    wristCorrection: [-0.3596, -0.3828, -0.4067, 0.7475],
  },
  CENTRE_LOW: {
    description: "Centred and low, where a base hand sits",
    target: [-0.05, 1.16, 0.24],
    shoulder: [19.0835, 61.2447, 3.1334],
    elbow: [56.1289, 46.0405, 24.8628],
    wristCorrection: [-0.6888, -0.5797, -0.1714, 0.4002],
  },
  CENTRE_MID: {
    description: "Centred, just above the base hand, where a dominant hand taps down",
    target: [-0.04, 1.29, 0.25],
    shoulder: [-14.846, 19.562, 22.266],
    elbow: [69.0825, -23.6732, -32.9116],
    wristCorrection: [-0.4265, -0.2014, 0.3133, 0.8242],
  },
  EAR: {
    description: "Beside the ear",
    target: [-0.19, 1.57, 0.02],
    shoulder: [-21.0234, 59.2734, -48],
    elbow: [0, 3.2813, -0.6094],
    wristCorrection: [0.3323, -0.3991, 0.4435, 0.7305],
  },
  NOSE: {
    description: "At the nose",
    target: [-0.02, 1.565, 0.115],
    shoulder: [12.2691, 82.9824, -68.791],
    elbow: [28.5979, 30.237, 8.6448],
    wristCorrection: [-0.0482, -0.6477, 0.4708, 0.597],
  },
  CHEEK: {
    description: "On the dominant cheek",
    target: [-0.065, 1.545, 0.085],
    shoulder: [-34.7535, 80.3143, -14.7052],
    elbow: [23.3855, 6.7328, -3.0034],
    wristCorrection: [0.1481, -0.5507, 0.4234, 0.7039],
  },
  BROW: {
    description: "At the brow, above the eye",
    target: [-0.045, 1.625, 0.095],
    shoulder: [-29.1013, 78.8031, -41.2811],
    elbow: [32.3919, 3.327, 14.5012],
    wristCorrection: [0.1362, -0.4128, 0.4485, 0.781],
  },
  NECK: {
    description: "At the throat",
    target: [-0.045, 1.465, 0.085],
    shoulder: [-58.18, 52.7684, 28.3603],
    elbow: [24.8066, -18.516, -34.0337],
    wristCorrection: [0.2501, -0.2614, 0.3633, 0.8586],
  },
  CHEST_OUT: {
    description: "A hand's depth in front of the upper chest",
    target: [-0.07, 1.31, 0.2],
    shoulder: [-4.8807, 20.8094, 16.2984],
    elbow: [47.7919, -24.0349, -36.782],
    wristCorrection: [-0.352, -0.1492, 0.324, 0.8653],
  },
  WAIST: {
    description: "At the waist",
    target: [-0.13, 1.03, 0.16],
    shoulder: [0.1262, -11.5423, 13.0094],
    elbow: [92.2967, -52.2622, -57.6295],
    wristCorrection: [-0.7549, -0.0795, 0.4563, 0.4643],
  },
  CONTRA_CHEST: {
    description: "Across the midline, on the non-dominant side of the chest",
    target: [0.07, 1.3, 0.17],
    shoulder: [-17.9947, 78.1158, 11.7335],
    elbow: [73.0411, -2.15, -10.1937],
    wristCorrection: [-0.3621, -0.5177, 0.4567, 0.6263],
  },
  CONTRA_SHOULDER: {
    description: "Across the body at the non-dominant shoulder",
    target: [0.09, 1.38, 0.13],
    shoulder: [-32.5691, 96.9734, -3.4203],
    elbow: [59.7186, -28.3325, -9.6061],
    wristCorrection: [0.0334, -0.3284, 0.6304, 0.7026],
  },
  ABOVE_HEAD: {
    description: "Above the head",
    target: [-0.16, 1.76, 0.12],
    shoulder: [-44.0603, 65.8731, -42.3854],
    elbow: [26.5289, 14.3912, 44.4401],
    wristCorrection: [0.1006, -0.3972, 0.2652, 0.8728],
  },
  SIDE_HIGH: {
    description: "Out to the dominant side at head height",
    target: [-0.33, 1.45, 0.16],
    shoulder: [-14.365, 11.4512, 5.6146],
    elbow: [26.1773, -5.9995, 8.8854],
    wristCorrection: [-0.1118, -0.05, -0.0824, 0.989],
  },
  SIDE_LOW: {
    description: "Out to the dominant side and low",
    target: [-0.27, 1.1, 0.2],
    shoulder: [13.8856, 22.6497, 28.2025],
    elbow: [34.9448, 36.8079, 46.198],
    wristCorrection: [-0.5138, -0.3095, -0.5878, 0.5429],
  },
  CENTRE_HIGH: {
    description: "Centred and high, in front of the chin",
    target: [-0.03, 1.42, 0.26],
    shoulder: [-37.5535, 26.5973, 31.8786],
    elbow: [64.1189, -21.8877, -23.4678],
    wristCorrection: [-0.2306, -0.222, 0.2463, 0.9148],
  },
  OUT_FAR: {
    description: "Well forward, where a sign pushes away to",
    target: [-0.2, 1.28, 0.4],
    shoulder: [-7.9822, 54.9134, 2.566],
    elbow: [30.3904, 34.8114, 61.423],
    wristCorrection: [-0.5318, -0.4766, -0.2937, 0.6354],
  },
  FACE_HIGH: {
    description: "In front of the face, off the midline so two hands clear each other",
    target: [-0.1, 1.6, 0.2],
    shoulder: [-47.2125, 79.154, 3.8007],
    elbow: [31.8556, -15.332, 24.2522],
    wristCorrection: [0.0456, -0.4196, 0.1892, 0.8866],
  },
  FACE_LOW: {
    description: "In front of the jaw, off the midline so two hands clear each other",
    target: [-0.1, 1.44, 0.2],
    shoulder: [-16.7645, 68.6196, 15.8526],
    elbow: [27.0144, 7.2243, 2.8692],
    wristCorrection: [-0.1719, -0.6062, 0.0734, 0.7731],
  },
} as const satisfies Record<string, SolvedLocation>;

export type LocationName = keyof typeof SOLVED_LOCATIONS;
