/**
 * GENERATED by tools/ingest-verdicts.ts -- do not edit by hand.
 *
 * What credentialed reviewers have said about the signs. Empty, and honestly
 * so: no Deaf reviewer has looked at any sign in this library. Every sign
 * therefore stays `unvalidated`, whatever its fidelity rating or the linter says.
 *
 * Run `pnpm review:ingest <file>` with a filled-in verdicts file to add to it.
 */

import type { Verdict } from './review.js';

export const VERDICTS: readonly Verdict[] = [];
