"""Pins the Python forward kinematics to the TypeScript implementation.

Two implementations of the same maths drift, and a drifting skeleton silently
corrupts every clip the pipeline produces. The fixture is generated by
``pnpm export:data``; regenerate it whenever the skeleton changes, and this
test will say whether the pipeline still agrees.
"""

from __future__ import annotations

import json

import numpy as np
import pytest

from signflow_pipeline.skeleton import DATA, load_skeleton, solve_fk, tip_positions

REFERENCE = json.loads((DATA / "skeleton" / "fk-reference.json").read_text())


@pytest.mark.parametrize("case", REFERENCE["poses"], ids=lambda c: c["name"])
def test_joint_positions_match_typescript(case: dict) -> None:
    sk = load_skeleton()
    pose = {name: np.asarray(q) for name, q in case["pose"].items()}
    positions, _ = solve_fk(pose, sk)

    worst_joint, worst = "", 0.0
    for name, expected in case["joints"].items():
        got = positions[sk.index[name]]
        error = float(np.linalg.norm(got - np.asarray(expected)))
        if error > worst:
            worst_joint, worst = name, error

    assert worst < 1e-7, f"{case['name']}: {worst_joint} differs by {worst * 1000:.4f}mm"


@pytest.mark.parametrize("case", REFERENCE["poses"], ids=lambda c: c["name"])
def test_fingertips_match_typescript(case: dict) -> None:
    sk = load_skeleton()
    pose = {name: np.asarray(q) for name, q in case["pose"].items()}
    positions, rotations = solve_fk(pose, sk)
    tips = tip_positions(positions, rotations, sk)

    for name, expected in case["tips"].items():
        got = tips[sk.tip_index[name]]
        assert float(np.linalg.norm(got - np.asarray(expected))) < 1e-7, name


def test_reference_covers_the_whole_skeleton() -> None:
    # A fixture that only exercised the arm would let the rest drift unnoticed.
    sk = load_skeleton()
    assert set(REFERENCE["poses"][0]["joints"]) == set(sk.names)
    assert REFERENCE["version"] == sk.version
